### ISSUE TITLE
unresolved functions

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaGPU/CUDAnative.jl#10]
I'm not sure if I'm encountering two different problems here.
But the first is encountered while doing something like this:
```Julia
for dims in ((4048,), (1024,1024), (77,), (1923,209))
    for T in (Float32,)
        A = GPUArray(rand(Float32, (4048,))) # replace with T and dims for error, works otherwise!
        @test sum(A) ≈ sum(Array(A))
        @test maximum(A) ≈ maximum(Array(A))
        @test minimum(A) ≈ minimum(Array(A))
        @test sumabs(A) ≈ sumabs(Array(A))
        @test prod(A) ≈ prod(Array(A))
    end
end
# yields
ERROR: No kernel image available/suitable for GPU (CUDA error #209, ERROR_NO_BINARY_FOR_GPU)
ptxas fatal   : Unresolved extern function 'julia_mod1_64892'
````
While trying to reduce the example, I ran into this guy:
```Julia
using CUDAnative, CUDAdrv
@target ptx function kernel(out)
    wid, lane = fldmod1(threadIdx().x, warpsize)
    out[1] = wid
    nothing
end
dev = CuDevice(0)
ctx = CuContext(dev)
d_out = CuArray(Int32, 1)
@cuda (1,1) kernel(d_out)
julia> fldmod1(Int32(1), Int32(1))
LLVM ERROR: Program used external function 'julia_mod1_64792' which could not be resolved! #quits Julia
```
Seems like some target selection doesn't work cleanly ;)
starting with `cujulia --compilecache=no --precompiled=no` doesn't help.

**Comment by maleadt** [comment]
Known issue, see #11 (`bugs/host_after_ptx.jl`). Using a method after it has been compiled for a different target is currently broken, because codegen doesn't know about the target and doesn't keep its caches separate.

Your first issue is bound to be similar, but the other way around. I could hack around it some more, but it's [pretty hacky already](https://github.com/JuliaGPU/julia/blob/1027948fb198384f9cf4d1c40fb5af61f766f820/src/codegen.cpp#L2992-L3006), so I'd rather spend time on figuring out a proper fix. Keep an eye on #11 for progress.

**Comment by maleadt** [comment]
FYI, this has been fixed.
