### ISSUE TITLE
Source build requirement

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CUDAnative.jl#106]
Known issue, obviously, but I wanted to track the status of it somewhere.

@maleadt can you remind me what your planned workaround was, and also why we can't fix this in Base (if I'm remembering our conversation correctly)?

**Comment by maleadt** [comment]
The issue is actually maleadt/LLVM.jl#17 -- CUDAnative.jl itself is already compatible with non-source builds.

Summarizing that issue: we can't build LLVM.jl's C++ deps because of C++. We need to build it in the same environment LLVM (and thus Julia) was built in. During JuliaCon @staticfloat hacked the buildbot to allow to build those LLVM.jl deps, but AFAIK that buildbot isn't used to build Julia yet so this won't help us. IIUC the proper solution is Bindeps2, but I have no idea how that's progressing (as in, I know the package is somewhat usable already, but I don't know what kind of environment it is building with -- this is very important for LLVM.jl because of the aforementioned C++ issues).
