### ISSUE TITLE
Supported compute capabilities.

### ISSUE THREAD

**Issue by xanfus** [JuliaGPU/CUDAnative.jl#141]
Can i manually add v"2.0.0" to capabilities collection as a workaround?

**Comment by maleadt** [comment]
No, neither the CUDA toolkit nor the LLVM NVPTX back-end support this compute capability anymore.

**Comment by Cody-G** [comment]
I was also trying to use a device with compute capability 2.0 and I was a bit confused by this because `Pkg.build()` completes without error.  I don't get an error unless I call certain functions on `CuArray`s.  It looks like [this](https://github.com/JuliaGPU/CUDAnative.jl/blob/master/deps/build.jl#L118) line in the build script should have thrown an error.  Any idea why it didn't?  It would be nice to get a build error if 2.0 devices are unsupported.  Thanks!

**Comment by maleadt** [comment]
The build script doesn't assume a device, but only configures the package in terms of the CUDA, LLVM and Julia versions. That line probably didn't throw an error, because your toolchain _does_ support certain devices, just not the one you're trying to use with it (ie. a device below sm_20). The build script should have logged the supported devices when run with `TRACE=true`.

**Comment by Cody-G** [comment]
I see, thanks for your quick reply!  The device is a Tesla M2090, which is not below sm_20.  It's exactly equal to sm_20.  So sm_20 is not supported?  I'll run with `TRACE=true` and see what it looks like.

**Comment by maleadt** [comment]
>  So sm_20 is not supported?

Depends on your CUDA version: sm_20 is only supported [up until CUDA 8.0](https://github.com/JuliaGPU/CUDAapi.jl/blob/9f7a24d5d5e87be62e30dc1abf7949340b182914/src/compatibility.jl#L66-L87). If you are using CUDA 8.0, this is a bug, please build with `TRACE=true` (don't forget `--compilecache=no`) and post the log.

**Comment by Cody-G** [comment]
I'm using CUDA 7.5 so this may be a bug.  I've seen similar behavior on a different machine with CUDA 8.0, so 7.5 vs 8.0 doesn't make a difference.  I'll open a new issue with the log.
