### ISSUE TITLE
Building on Ubuntu Bionic (LTS)

### ISSUE THREAD

**Issue by fghorow** [JuliaGPU/CUDAnative.jl#186]
Has anyone successfully installed on Ubuntu Bionic? If so, what was the magic combination of driver, julia, CUDAnative, and whatever other dependency versions that was required.

I'm a newbie to Julia, and CUDAnative, but want to see if I can speed up a HUGE tomography problem using a 1060.

TIA for any help you might be able to provide!

**Comment by vchuravy** [comment]
Open discussions questions like these are better suited for https://discourse.julialang.org

In general building Julia 0.6 from source should work on any Linux version with current driver and CUDA version (see http://juliagpu.github.io/CUDAnative.jl/stable/#Installation-1)

**Comment by maleadt** [comment]
> should work on any Linux version with current driver and CUDA version

Echoing this. If you encounter actual issues, feel free to open a specific issue for us to act on.

**Comment by maleadt** [comment]
Well, the mysterious error is actually pretty clear:
```
InvalidIRError("calls the Julia runtime", ("jl_undefined_var_error",   tail call void @jl_undefined_var_error
```

And indeed, checking your code with eg. `@device_code_warntype` reveals that `getGlobalIdx_3D_3D` returns `Any` because of a typo: `return threadID` instead of `threadId`.

Admittedly, this isn't a very user friendly experience, but we're working on that. It has nothing to do with any installation issue though, let alone dependence on a Ubuntu version. Don't hesitate to ask questions like these though, but as Valentin mentions Discourse is a better platform for that :slightly_smiling_face:

**Comment by fghorow** [comment]
Sigh. Thank you very much! I'm embarrassed to admit how long I've been chasing this one. :-(
I will indeed send such questions to Discourse. Many thanks again!
