### ISSUE TITLE
Segfault when using @device_code_lowered

### ISSUE THREAD

**Issue by KristofferC** [JuliaGPU/CUDAnative.jl#308]
Testing the hello world example and executing:

<img width="834" alt="screenshot 2019-01-02 at 22 45 58" src="https://user-images.githubusercontent.com/1282691/50614175-3370bb80-0ee0-11e9-9094-86a47c57baec.png">

Sorry for screenshot having troubles copy pasting from the remote session.

**Comment by maleadt** [comment]
Can't reproduce, got some details (OS, versions, build type)?

The trace goes back to the Julia JIT... Just a guess, are you doing `@device_code_lowered hello_world()`? Because then GPU code gets compiled for the CPU which indeed might just segfault. You need to `@device_code_lowered @cuda [args...] hello_world()`

**Comment by maleadt** [comment]
> Just a guess, are you doing `@device_code_lowered hello_world()`?

I didn't see the first line of your screenshot, which confirms this. GPU code isn't CPU executable.

**Comment by KristofferC** [comment]
Ah, I didn't realize the `@cuda` was needed, thanks.
