### ISSUE TITLE
@cuprintf format string sensitive to variable position

### ISSUE THREAD

**Issue by colbec** [JuliaGPU/CUDAnative.jl#39]
Considering the following toy code that element-wise multiplies up each value in the matrix, note that the same pair of variables are printed each time, with slight variation in the position in the string "i j j i". Format A prints correctly , but format B has reports zeros for both i and j. It seems to be tied to the position in the format string, not to one variable or the other, or the order in which they are defined in the kernel.
```
using CUDAdrv, CUDAnative

function kernel_mmul(a, c)
    one = 1
    two = 2
    i = (blockIdx().x-1) * blockDim().x + threadIdx().x
    j = (blockIdx().y-1) * blockDim().y + threadIdx().y
    c[i,j] = a[i,j].*3
    @cuprintf("A %d %ld %d %ld\n",i,j,j,i) # format A
    @cuprintf("B %d %d %d %d\n",i,j,j,i)  # format B    
    return nothing
end
dev = CuDevice(0)
ctx = CuContext(dev)
a = Int32[1 2 3; 2 3 1; 3 1 2]
d_a = CuArray(a)
d_c = similar(d_a) 
@cuda ((1,1),(3,3)) kernel_mmul(d_a, d_c)
c = Array(d_c)
println(a)
println(c)
destroy(ctx)
```
with output:
```
A 1 1 1 1
A 2 1 1 2
A 3 1 1 3
A 1 2 2 1
A 2 2 2 2
A 3 2 2 3
A 1 3 3 1
A 2 3 3 2
A 3 3 3 3
B 1 0 1 0
B 2 0 1 0
B 3 0 1 0
B 1 0 2 0
B 2 0 2 0
B 3 0 2 0
B 1 0 3 0
B 2 0 3 0
B 3 0 3 0
Int32[1 2 3; 2 3 1; 3 1 2]
Int32[3 6 9; 6 9 3; 9 3 6]

```

**Comment by maleadt** [comment]
Difficult to fix, as this is due to how the underlying `vprintf` works. We also can't sensibly verify the formatting string, as we can't throw from the generated function. Unless we'd just generate a `trap`, but that doesn't seem like a good UI either? We'd also need to parse the formatting string, which might be non-trivial (especially so because CUDA's printf is a non standards compliant implementation).

The reason you're seeing 0 values is because your printing 2 times 32-bits from a 64-bit value, and the upper 32-bits are zero because we're dealing with small values. The discrepancy you mentioned on Discourse is curious though, and might be argument padding related.

**Comment by colbec** [comment]
Thank you, this makes sense and is very helpful. I have found after multiple tests that one thing that works while following through indexes is to let the system play with its types as it wants, and just before doing anything important to the final result, coerce the type back to Int32. This handles very large indices, well within my testing needs. Here is a revised version of my testing script in case it is of interest to others going down the same path:
```
using CUDAdrv, CUDAnative
using Base.Test

function kernel_mmul(a, c, tval)
    bix = blockIdx().x
    bdx = blockDim().x
    biy = blockIdx().y
    bdy = blockDim().y
    tix = threadIdx().x
    tiy = threadIdx().y
    i = Int32((bix-1) * bdx + tix)
    j = Int32((biy-1) * bdy + tiy)
    #t = convert(AbstractString,typeof(i))
    c[i,j] = Int32(a[i,j].*tval)
    @cuprintf("C %d %d %d %d\n",i,j,j,i)
    @cuprintf("D %d %d %d %d %d %d\n",bix,bdx,biy,bdy,tix,tiy)
    @cuprintf("E %d\n",c[i,j])
    #@cuprintf("F %s\n",t)
    
    return nothing
end

dev = CuDevice(0)
ctx = CuContext(dev)
a = Int32[1 2 3; 2000 3 1; 3 1 2]
d_a = CuArray(a)
d_c = similar(d_a)
tval = 20000
@cuda ((1,1),(3,3)) kernel_mmul(d_a, d_c, tval)
c = Array(d_c)
println(a)
println(c)
@test a.*tval ≈ c
destroy(ctx)

```
Note that in this case "%ld" in the formatting string seems to bite off too many bits, so "%d" is relevant. A downside of using UInts for indices is that they don't print intuitively, all come out as hex which is less readable. Also Julia in the kernel does not seem to like a request to `typeof()` but that is a minor issue. From a debugging point of view it might be nice to have the `cudaprintf` statements interleaved on output, but that is just a matter of postprocessing.

**Comment by maleadt** [comment]
> to let the system play with its types as it wants, and just before doing anything important to the final result, coerce the type back to Int32

While forcing the type at the latest opportunity is a fine way to start out, mixing 32-bit and 64-bit integers can have a cost: converting from 32 to 64 bit is an additional instruction (and hence might result in extra register pressure, at least at the PTX level), while converting from 64 to 32 bit forces a checked conversion + exception (a trap basic-block with the current JIT). That's why optimized library code like the [reduce example](https://github.com/JuliaGPU/CUDAnative.jl/blob/bbf223ac57585c832eda7b7af69f7b27d4162e0a/examples/reduce/reduce.jl#L13-L21) manually manages the types to avoid such conversions.

> Also Julia in the kernel does not seem to like a request to typeof() but that is a minor issue.

Inference should constprop this, the problem is that you're converting to a string, which is heap allocated (a big no no with CUDAnative).
