### ISSUE TITLE
Can't broadcast complex Array with exp

### ISSUE THREAD

**Issue by navidcy** [JuliaGPU/CUDAnative.jl#430]
(I'm not sure this issue belongs here -- please advise me accordingly.)

The issue is demonstrated below:

```julia
julia> a = rand(2, 2) + im*rand(2, 2)
2×2 Array{Complex{Float64},2}:
 0.465535+0.449849im  0.381765+0.0849708im
 0.387269+0.847888im  0.380261+0.375675im

julia> b = CuArray(a)
2×2 CuArray{Complex{Float64},2}:
 0.465535+0.449849im  0.381765+0.0849708im
 0.387269+0.847888im  0.380261+0.375675im

julia> exp.(a)
2×2 Array{Complex{Float64},2}:
   1.4344+0.692625im  1.45958+0.124321im
 0.974459+1.10455im   1.36066+0.536653im

julia> exp.(b)
ERROR: MethodError: no method matching exp(::Complex{Float64})
You may have intended to import Base.exp
Closest candidates are:
  exp(::Float32) at /home/navid/.julia/packages/CUDAnative/gJDZI/src/device/cuda/math.jl:90
  exp(::Float64) at /home/navid/.julia/packages/CUDAnative/gJDZI/src/device/cuda/math.jl:89
Stacktrace:
 [1] _broadcast_getindex at ./broadcast.jl:578 [inlined]
 [2] getindex at ./broadcast.jl:511 [inlined]
 [3] copy at ./broadcast.jl:787 [inlined]
 [4] materialize(::Base.Broadcast.Broadcasted{Base.Broadcast.ArrayStyle{CuArray},Nothing,typeof(CUDAnative.exp),Tuple{CuArray{Complex{Float64},2}}}) at ./broadcast.jl:753
 [5] top-level scope at none:0

julia>
```

**Comment by ali-ramadhan** [comment]
I think in general you have to use or broadcast over `CUDAnative.exp` but then the issue is that `CUDAnative.exp` is not defined for `Complex{Float64}`...

Not sure if CUDA provides a complex exponential (or complex math), would definitely be nice to have if possible.

I have some complex exponentials that I currently calculate on the CPU then move them them to a CuArray but it's part of model setup so does not need to be fast. But if I had to calculate them frequently, then I'm not sure what I would do. I guess split the calculation up using `real()` and `imag()` but that wouldn't be ideal...

https://github.com/JuliaGPU/CUDAnative.jl/blob/fc94cb321b76a3428c016c4e2ea8c6d681e8d308/src/device/cuda/math.jl#L87-L104

**Comment by benchislett** [comment]
Would I be able to add a few composite methods into `src/device/cuda/math.jl` for complex numbers?
For example,
```julia
...
@inline exp(x::Complex{Float64}) = exp(x.re) * (cos(x.im) + 1.0im * sin(x.im))
```

**Comment by jonathanBieler** [comment]
Same problem here with `abs`, I've tried to define it myself but without success.

**Comment by benchislett** [comment]
@jonathanBieler I've implemented it with the `hypot` function:
```julia
@inline CUDAnative.abs(x::Complex{Float64}) = CUDAnative.hypot(x.re, x.im)
```
