### ISSUE TITLE
AbstractGPUCompiler submodule

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/CUDAnative.jl#442]
To facilitate other GPU implementations like AMDGPUnative, we should create a AbstractGPUCompiler package to isolate reusable functionality in. For the time being, and while we're figuring out a good API for that, we could implement that package as a submodule of CUDAnative, and have AMDGPUnative depend on CUDAnative (or the submodule directly, if that's possible).

**Comment by vchuravy** [comment]
Maybe call it something like CompilerFramework or AbstractCompiler, since I am likely to use it as part of MCAnalyzer and other projects. But yeah I am excited about this

**Comment by jpsamaroo** [comment]
+1 to naming it something like CompilerFramework; I also have BPF and native codegen projects planned, so these sorts of names would make more sense.

Tim, did you end up talking with some of the Pkg people to see if it's currently feasible to depend on a subfolder of a repository (so that we can skip loading the CUDA-specific libraries)?
