### ISSUE TITLE
wrong sin is an unrecoverable error

### ISSUE THREAD

**Issue by MikeInnes** [JuliaGPU/CUDAnative.jl#93]
If I call `sin.(xs)` instead of `CUDAnative.sin.(xs)` with a GPUArray, for example, this gives an "invalid program counter" error that is persistent even once you've fixed the issue. It would be nice if CUDAnative could recover from this error without a restart.

**Comment by maleadt** [comment]
Sadly, this is extremely hard. These kine of errors, invalid program counter, access violations, memory errors, which are caused by loading memory from or jumping to invalid pointers (caused by passing a CPU pointer from a function) kill the context. The only fix is a hard device reset and construction of a new context. (This is also the case for exceptions, which generate a `trap` instruction, killing the GPU in similar ways.)

Alternatively, we could do more effort of detecting calls to CPU functions, methods in the CPU JIT (using a CodegenParam), or just scan the final IR for `inttoptr` (which is a sign of literal pointers to CPU functions being embedded).

**Comment by MikeInnes** [comment]
How about automatically resetting the device/stream if one of these kinds of errors is thrown?

**Comment by maleadt** [comment]
> How about automatically resetting the device/stream if one of these kinds of errors is thrown?

Then what about every existing allocation suddenly becoming invalid?

**Comment by maleadt** [comment]
Ah, now I remember all the details. Turns out most of the API is utterly broken after a (sticky) error:

```
julia> dev = CuDevice(0)
CuDevice(0): GeForce GTX TITAN

julia> ctx = CuContext(dev)
ERROR: CUDA error: invalid program counter (code #718, ERROR_INVALID_PC)
```

I found some [sources](https://stackoverflow.com/questions/43659314/how-to-reset-cuda-error-to-success-with-driver-api) which promise the primary context API still works, but alas, after switching `default_context` to be a primary context:

```
julia> @assert first(CUDAdrv.pctx_instances[pctx]).value == CUDAnative.default_context[]

julia> pctx = CuPrimaryContext(CUDAnative.default_device[])
CUDAdrv.CuPrimaryContext(CUDAdrv.CuDevice(0, 0))

julia> @assert first(CUDAdrv.pctx_instances[pctx]).value == CUDAnative.default_context[]

julia> CUDAdrv.@apicall(:cuDevicePrimaryCtxReset, (CUDAdrv.CuDevice_t,), CUDAnative.default_device[])

julia> CuContext(pctx)
ERROR: CUDA error: invalid program counter (code #718, ERROR_INVALID_PC)
```

Fun fact, even `cudaDeviceReset` (from the runtime toolkit) doesn't help:

```
julia> ccall((:cudaDeviceReset, :libcudart), Cint, ())
0

julia> CUDAdrv.state(pctx)
(0x00000000, false)

julia> CuContext(pctx)
ERROR: CUDA error: invalid program counter (code #718, ERROR_INVALID_PC)
```

So yeah, not going to happen I'm afraid.
